#!/bin/bash
set -e

export DIR=`dirname $0`
export LIB_DIR="${DIR}/lib"

run_subcommand() {
  local SUBCOMMAND=$1
  
  case $SUBCOMMAND in
    help | init | clean | sync | oneshot) 
      sh "${LIB_DIR}/${SUBCOMMAND}.sh" "${@:2}"
      exit;;
    *)
      echo "No such action as '${SUBCOMMAND}'"
      exit -1;;
  esac
}

if [ "$#" -eq 0 ]; then
  run_subcommand help
else 
  run_subcommand $@
fi